/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as OpinionesRouteImport } from './routes/opiniones'
import { Route as IndexRouteImport } from './routes/index'

const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionesRoute = OpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opiniones': typeof OpinionesRoute
  '/portafolio': typeof PortafolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opiniones': typeof OpinionesRoute
  '/portafolio': typeof PortafolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opiniones': typeof OpinionesRoute
  '/portafolio': typeof PortafolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opiniones' | '/portafolio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opiniones' | '/portafolio'
  id: '__root__' | '/' | '/opiniones' | '/portafolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpinionesRoute: typeof OpinionesRoute
  PortafolioRoute: typeof PortafolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opiniones': {
      id: '/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof OpinionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpinionesRoute: OpinionesRoute,
  PortafolioRoute: PortafolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
